name: CI

on: push

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest
    container: ruby:3.0.1

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ci_sandbox
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1.91.0
        with:
          bundler-cache: true

      - name: Setup DB
        run: bundle exec rake db:setup

      - name: Run RuboCop
        run: bundle exec rubocop --parallel

      - name: Run Tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://ci_sandbox:password@postgres/ci_sandbox_test
